### ISSUE TITLE
Locale name return blank

### ISSUE THREAD

**Issue by leandromatos** [felixzapata/gulp-pug-i18n#1]
In example in readme, `#{$localeName}` return blank.

```
body
  h1 #{$i18n.hello.world}!
  p Using locale #{$localeName}
```

How to get name of locale in file?

**Comment by felixzapata** [comment]
hi @leandromatos , I will take a look as soon as possible.

**Comment by felixzapata** [comment]
@leandromatos I've updated the plugin to fix this issue. The readme file had the example but was not in the plugin. Now, the `localeName` will be returned to the template if there are locales files.

**Comment by leandromatos** [comment]
Thanks @felixzapata ;)

**Comment by leandromatos** [comment]
The return of `$localeName` continues null =(

**Comment by felixzapata** [comment]
hi @leandromatos, is it ok?

**Comment by leandromatos** [comment]
Yes, but I used NPM for install package, only after I saw that the package I installed is from someone else and has the same name, however, this package not returns `localeName` =(

**Comment by leandromatos** [comment]
@felixzapata, Why do not you put your package in NPM? Even if you have to rename it, it's much easier to use on projects.

**Comment by felixzapata** [comment]
hi @leandromatos , I started this plugin three years (to create the Gulp version of the Grunt version) ago without finished it. Finally, last year I resumed the plugin and when I had something to publish I discovered the other and I thought myself: "well, maybe it is not necessary".

But if you find useful I can think another name and publish it via NPM.

Regards.

**Comment by felixzapata** [comment]
@leandromatos [I've published the plugin](https://www.npmjs.com/package/gulp-i18n-pug)

**Comment by leandromatos** [comment]
Thanks @felixzapata !
