### ISSUE TITLE
localeExtension options is getting ignored

### ISSUE THREAD

**Issue by fschucht** [felixzapata/gulp-pug-i18n#4]
When using `gulp-pug-i18n` the `localeExtension` options is getting ignored and the html files are always created in the schema of `filename.locale.html`.

This is my task code:
```js
const PATHS = {
  dist: 'dist',
  templates: 'src/templates/*.pug'
}

gulp.task('translate-templates', () => {
  const options = {
    i18n: {
      dest: PATHS.dist,
      locales: `${PATHS.dist}/translations/*.json`,
      localeExtension: false
    }
  }
  return gulp.src(PATHS.templates)
    .pipe(pugI18n(options))
    .pipe(gulp.dest(PATHS.dist))
})
```

**Comment by felixzapata** [comment]
Hi @fschucht it is works. The problem is I made a mistake with the name of the plugin in the other [issue](https://github.com/felixzapata/gulp-i18n-pug/issues/3) and I was not using my plugin.
