### ISSUE TITLE
Too many messages

### ISSUE THREAD

**Issue by Akiyamka** [felixzapata/gulp-pug-i18n#7]
`gutil.log(...)` too much spam in the terminal. Perhaps it's better not to write anything without extreme need, and even if there is one, you can combine the output into one line.
![screenshot from 2018-03-29 14-28-59](https://user-images.githubusercontent.com/6587585/38086574-9130dade-335d-11e8-85d9-810c0ef30391.png)

**Comment by felixzapata** [comment]
hi, thanks for the suggestion, I will take a look.

**Comment by felixzapata** [comment]
@Akiyamka what do you think about having a verbose (`false` by default) output like this?

![captura de pantalla 2018-03-30 a las 16 27 52](https://user-images.githubusercontent.com/997038/38141264-9538c0e4-3437-11e8-99cc-f208e066d653.png)

and a default output like this:

![no-verbose](https://user-images.githubusercontent.com/997038/38141285-aa0112d8-3437-11e8-95ad-f5ec459a741a.png)

**Comment by Akiyamka** [comment]
@felixzapata much better!

**Comment by felixzapata** [comment]
@Akiyamka I've released version 1.1.0
